on:
  push:
    branches:
      - '*'
      - '**'
      - '!releases/*'
      - '!releases/*/*'
      - '!releases/**'
      - '!main'
      - '!develop'

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Git Checkout
      - uses: actions/setup-go@v3
        name: Initialize Development environment
        with:
          go-version: '1.18.3' # The Go version to download (if necessary) and use.
      - run:  go mod tidy
        name: Download dependencies
      - run:  go test ./...
        name: Execute

  build:
    runs-on: ubuntu-latest
    needs:
      - unit_testing
    steps:
      - uses: actions/checkout@v3
        name: Git Checkout
      - uses: actions/setup-go@v3
        name: Initialize Development environment
        with:
          go-version: '1.18.3' # The Go version to download (if necessary) and use.
      - run:  go mod tidy
        name: Download dependencies
      - run:  go build
        name: Build application
      - name: Upload application into Github artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./versioner

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
        name: Git Checkout
      - uses: actions/download-artifact@master
        name: Download application from artifacts
        with:
          name: dist
          path: versioner
      - name: Upload application into S3
        uses: medlypharmacy/s3-artifacts-action@master
        with:
          resource_type: "FILE"
          source_path: './versioner'
          exclude_repo_from_destination_path: true
          destination_path: "/public/versioner/2.0.0.${{ github.run_id }}.${{ github.run_number }}-RELEASE"
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_s3_bucket_name: ${{ secrets.AWS_BUCKET }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}